import Poly.Equalizers

/-
============================================================
Poly Project
File: Poly/Coequalizers.lean
============================================================

This file constructs coequalizers in the category `PolyC` of polynomial
functors / containers, following Theorem 5.44 and Exercise 5.45 of
*Polynomial Functors*.

Given parallel lenses

  f g : P ⟶ Q,

a coequalizer is an object `C` together with a map

  q : Q ⟶ C

such that

1. `f ≫ q = g ≫ q`, and
2. for every `h : Q ⟶ R` with `f ≫ h = g ≫ h`, there exists a unique
   `u : C ⟶ R` with `q ≫ u = h`.

Book construction:
The book constructs coequalizers by taking:

  • connected components / a quotient on positions, and
  • limits of direction-sets over each connected component.

In the positions-and-directions presentation, the quotient on positions is
generated by identifying

  f.onShapes p ~ g.onShapes p

for every position `p : P.A`. A direction over a quotient component is a
compatible family of directions over all representatives in that component.
This compatible family is the Type-level version of the book's limit of
direction-sets.

Universe note:
The direction type of a coequalizer component is a dependent product over
positions in that component. If positions live in `Type u` and directions live
in `Type v`, this product naturally lives in `Type (max u v)`. Therefore this
file states coequalizers for objects whose direction universe is already large
enough:

  P Q : PolyC.{u, max u v}

This is the Lean-native size discipline corresponding to the book's set-level
construction.

Terminology note:
the codebase still uses the internal field names

  • `A`        = positions,
  • `B a`      = directions at position `a`,
  • `onShapes` = forward map on positions,
  • `onPos`    = backward pullback map on directions.

Human-facing mathematical descriptions should use positions and directions.
============================================================
-/

open CategoryTheory

namespace PolyC

universe u v u₁ u₂

/-
==============================================================================
Small helper lemmas for heterogeneous transport
==============================================================================
-/

/-- Function extensionality across a casted domain. -/
private lemma heqFunOfCast
    {α β : Type u₁} {γ : Type u₂}
    (h : α = β)
    (F : α → γ)
    (G : β → γ)
    (H : ∀ x : α, F x = G (cast h x)) :
    HEq F G := by
  cases h
  exact heq_of_eq (funext H)

/-- A value and its raw cast are heterogeneously equal. -/
private lemma heq_cast
    {α β : Type u₁}
    (h : α = β) (x : α) :
    HEq x (cast h x) := by
  cases h
  rfl

/-- Transport along a reflexive position equality is the identity. -/
private lemma castQPos_eq_self
    {R : PolyC.{u, max u v}}
    {x : R.A}
    (h : x = x) (r : R.B x) :
    castQPos (Q := R) h r = r := by
  have hh : h = rfl := proof_irrel h rfl
  cases hh
  rfl

/-- Two casts of the same direction along two paths with the same endpoint compose as expected. -/
private lemma castQPos_after_cast_eq
    {R : PolyC.{u, max u v}}
    {x y z : R.A}
    (hxy : x = y)
    (hyz : y = z)
    (hxz : x = z)
    (r : R.B x) :
    castQPos (Q := R) hyz (cast (congrArg R.B hxy) r)
      =
    cast (congrArg R.B hxz) r := by
  cases hxy
  cases hyz
  have hh : hxz = rfl := proof_irrel hxz rfl
  cases hh
  rfl

/-- Casts of the same value along two position equalities are heterogeneously equal. -/
private lemma heq_two_castQPos
    {R : PolyC.{u, max u v}}
    {x y z : R.A}
    (hy : x = y) (hz : x = z)
    (r : R.B x) :
    HEq (castQPos (Q := R) hy r) (castQPos (Q := R) hz r) := by
  cases hy
  cases hz
  rfl


/--
A raw cast followed by `castQPos` is heterogeneously equal to the original
value.

This is useful in the uniqueness proof: `Hom.ext` gives us a raw `cast`,
while the definition of `coeqDesc` uses `castQPos`.
-/
private lemma heq_rawCast_castQPos_trans
    {R : PolyC.{u, max u v}}
    {x y z : R.A}
    (hxy : x = y) (hyz : y = z)
    (r : R.B x) :
    HEq r (castQPos (Q := R) hyz (cast (congrArg R.B hxy) r)) := by
  cases hxy
  cases hyz
  rfl

/--
Congruence for the dependent `onPos` field of a morphism.

If two morphisms are equal, their pullback maps on directions agree on
heterogeneously equal inputs.
-/
private lemma hom_onPos_congr
    {R S : PolyC.{u, max u v}}
    {F G : R ⟶ S}
    (hFG : F = G)
    (r : R.A)
    (qF : S.B (F.onShapes r))
    (qG : S.B (G.onShapes r))
    (hq : HEq qF qG) :
    F.onPos r qF = G.onPos r qG := by
  revert qF qG hq
  cases hFG
  intro qF qG hq
  cases hq
  rfl

/-
==============================================================================
A lightweight coequalizer predicate
==============================================================================
-/

/--
`IsCoequalizer f g q` says that `q : Q ⟶ C` is a coequalizer of the
parallel pair `f g : P ⟶ Q`.
-/
structure IsCoequalizer
    {P Q C : PolyC.{u, max u v}}
    (f g : P ⟶ Q) (q : Q ⟶ C) : Prop where
  condition : f ≫ q = g ≫ q
  desc :
    ∀ {R : PolyC.{u, max u v}} (h : Q ⟶ R),
      f ≫ h = g ≫ h →
      ∃! u : C ⟶ R, q ≫ u = h

section CoequalizerConstruction

variable {P Q : PolyC.{u, max u v}}

/-
==============================================================================
Step 1: Position quotient
==============================================================================

The coequalizer positions are connected components of the graph with vertices
`Q.A` and an edge from `f.onShapes p` to `g.onShapes p` for each `p : P.A`.
In Type, this is the equivalence closure of the generating relation.
-/

/-- Generating relation on positions of `Q`. -/
def CoeqBaseRel (f g : P ⟶ Q) : Q.A → Q.A → Prop :=
  fun x y => ∃ p : P.A, x = f.onShapes p ∧ y = g.onShapes p

/-- Equivalence closure of the generating position relation. -/
abbrev CoeqRel (f g : P ⟶ Q) : Q.A → Q.A → Prop :=
  Relation.EqvGen (CoeqBaseRel f g)

/-- Setoid generated by the coequalizer position relation. -/
def CoeqSetoid (f g : P ⟶ Q) : Setoid Q.A where
  r := CoeqRel f g
  iseqv := by
    refine ⟨?refl, ?symm, ?trans⟩
    · intro x
      exact Relation.EqvGen.refl x
    · intro x y hxy
      exact Relation.EqvGen.symm x y hxy
    · intro x y z hxy hyz
      exact Relation.EqvGen.trans x y z hxy hyz

/-- Positions of the coequalizer object. -/
abbrev CoeqA (f g : P ⟶ Q) : Type u :=
  Quot (CoeqSetoid f g)

/-- Quotient map on positions. -/
def coeqClass (f g : P ⟶ Q) : Q.A → CoeqA f g :=
  Quot.mk _

/-- One generating edge belongs to the position relation. -/
lemma coeqRel_step (f g : P ⟶ Q) (p : P.A) :
    CoeqRel f g (f.onShapes p) (g.onShapes p) := by
  refine Relation.EqvGen.rel
    (r := CoeqBaseRel f g)
    (x := f.onShapes p)
    (y := g.onShapes p)
    ?_
  exact ⟨p, rfl, rfl⟩

/-- The quotient map identifies the two position images of every source position. -/
lemma coeqClass_eq (f g : P ⟶ Q) (p : P.A) :
    coeqClass f g (f.onShapes p) = coeqClass f g (g.onShapes p) := by
  apply Quot.sound
  exact coeqRel_step f g p

/-
==============================================================================
Step 2: Direction limits over position components
==============================================================================

A direction over a quotient component `c` is a compatible family of directions,
one direction over every representative `q : Q.A` in the component `c`.

Compatibility says that for every generating edge `p : P.A`, the two ways of
pulling a compatible family back along `f` and `g` agree.
-/

/-- The underlying family of projections for a coequalizer direction. -/
def CoeqFam (f g : P ⟶ Q) (c : CoeqA f g) : Type (max u v) :=
  ∀ q : Q.A, coeqClass f g q = c → Q.B q

/-- Compatibility condition for a family of representative directions. -/
def CoeqCompatible (f g : P ⟶ Q) (c : CoeqA f g)
    (fam : CoeqFam f g c) : Prop :=
  ∀ p : P.A,
  ∀ hf : coeqClass f g (f.onShapes p) = c,
  ∀ hg : coeqClass f g (g.onShapes p) = c,
    f.onPos p (fam (f.onShapes p) hf)
      =
    g.onPos p (fam (g.onShapes p) hg)

/--
Direction type over a coequalizer position.

This is the Type-level limit of the diagram of direction-sets over the
connected component represented by `c`.
-/
abbrev CoeqB (f g : P ⟶ Q) (c : CoeqA f g) : Type (max u v) :=
  { fam : CoeqFam f g c // CoeqCompatible f g c fam }

/-- Extensionality for coequalizer directions. -/
lemma coeqB_ext {f g : P ⟶ Q} {c : CoeqA f g}
    (x y : CoeqB f g c)
    (h : ∀ q hq, x.1 q hq = y.1 q hq) :
    x = y := by
  apply Subtype.ext
  funext q hq
  exact h q hq

/-- Projection from the direction-limit object to a representative direction-set. -/
def coeqDirProj (f g : P ⟶ Q)
    (c : CoeqA f g)
    (q : Q.A)
    (hq : coeqClass f g q = c) :
    CoeqB f g c → Q.B q :=
  fun d => d.1 q hq

/-- Compatibility of the two projections associated to a generating edge. -/
theorem coeqDirCompat (f g : P ⟶ Q)
    (c : CoeqA f g)
    (d : CoeqB f g c)
    (p : P.A)
    (hf : coeqClass f g (f.onShapes p) = c)
    (hg : coeqClass f g (g.onShapes p) = c) :
    f.onPos p (coeqDirProj f g c (f.onShapes p) hf d)
      =
    g.onPos p (coeqDirProj f g c (g.onShapes p) hg d) := by
  exact d.2 p hf hg

/-- How a coequalizer direction behaves under transport of its quotient component. -/
private lemma CoeqB_cast_proj {f g : P ⟶ Q}
    {c₁ c₂ : CoeqA f g}
    (e : c₁ = c₂)
    (d : CoeqB f g c₁)
    (q : Q.A)
    (hq : coeqClass f g q = c₂) :
    (cast (congrArg (CoeqB f g) e) d).1 q hq
      =
    d.1 q (hq.trans e.symm) := by
  cases e
  rfl

/-
==============================================================================
Step 3: The coequalizer object and canonical map
==============================================================================
-/

/-- The coequalizer object. -/
def CoeqObj (f g : P ⟶ Q) : PolyC.{u, max u v} where
  A := CoeqA f g
  B := CoeqB f g

/--
The canonical coequalizer map `Q ⟶ CoeqObj f g`.

On positions it sends each position to its connected component. On directions
it uses the projection from the direction-limit object to the chosen
representative.
-/
def coeq (f g : P ⟶ Q) : Q ⟶ CoeqObj f g where
  onShapes := coeqClass f g
  onPos := fun q d => d.1 q rfl

/-
==============================================================================
Step 4: The coequalizer equation
==============================================================================
-/

/-- The canonical map coequalizes `f` and `g`. -/
theorem coeq_comp_eq (f g : P ⟶ Q) :
    f ≫ coeq f g = g ≫ coeq f g := by
  refine Hom.ext (f ≫ coeq f g) (g ≫ coeq f g) ?hShapes ?hDirs
  · funext p
    exact coeqClass_eq f g p
  · intro p
    let e :
        coeqClass f g (f.onShapes p)
          =
        coeqClass f g (g.onShapes p) :=
      coeqClass_eq f g p
    exact heqFunOfCast
      (h := congrArg (fun c : CoeqA f g => CoeqB f g c) e)
      ((f ≫ coeq f g).onPos p)
      ((g ≫ coeq f g).onPos p)
      (by
        intro d
        change
          f.onPos p (d.1 (f.onShapes p) rfl)
            =
          g.onPos p
            ((cast (congrArg (fun c : CoeqA f g => CoeqB f g c) e) d).1
              (g.onShapes p) rfl)
        have hproj :
            (cast (congrArg (fun c : CoeqA f g => CoeqB f g c) e) d).1
                (g.onShapes p) rfl
              =
            d.1 (g.onShapes p) e.symm := by
          calc
            (cast (congrArg (fun c : CoeqA f g => CoeqB f g c) e) d).1
                (g.onShapes p) rfl
                =
              d.1 (g.onShapes p)
                ((rfl :
                    coeqClass f g (g.onShapes p)
                      =
                    coeqClass f g (g.onShapes p)).trans e.symm) := by
                  exact
                    CoeqB_cast_proj
                      (f := f) (g := g)
                      e d (g.onShapes p)
                      (rfl :
                        coeqClass f g (g.onShapes p)
                          =
                        coeqClass f g (g.onShapes p))
            _ = d.1 (g.onShapes p) e.symm := by
                  have hproof :
                      ((rfl :
                          coeqClass f g (g.onShapes p)
                            =
                          coeqClass f g (g.onShapes p)).trans e.symm)
                        =
                      e.symm := by
                    apply proof_irrel
                  cases hproof
                  rfl
        rw [hproj]
        exact d.2 p rfl e.symm)

/-
==============================================================================
Step 5: Position map induced by a coequalizing arrow
==============================================================================

Given `h : Q ⟶ R` satisfying `f ≫ h = g ≫ h`, the position map of the
factorization `CoeqObj f g ⟶ R` is induced by quotient recursion on
positions.
-/

private lemma coeqDescShape_respects_rel
    {R : PolyC.{u, max u v}}
    (f g : P ⟶ Q)
    (h : Q ⟶ R)
    (heq : f ≫ h = g ≫ h)
    {x y : Q.A}
    (hxy : CoeqRel f g x y) :
    h.onShapes x = h.onShapes y := by
  induction hxy with
  | refl x =>
      rfl
  | rel x y hbase =>
      rcases hbase with ⟨p, hx, hy⟩
      subst hx
      subst hy
      have hsFun : (f ≫ h).onShapes = (g ≫ h).onShapes :=
        congrArg (fun k => k.onShapes) heq
      have hs : (f ≫ h).onShapes p = (g ≫ h).onShapes p :=
        congrArg (fun fn => fn p) hsFun
      simpa [PolyC.comp] using hs
  | symm x y _ ih =>
      exact ih.symm
  | trans x y z _ _ ihxy ihyz =>
      exact ihxy.trans ihyz

/-- The position map induced out of the coequalizer position quotient. -/
def coeqDescShape
    {R : PolyC.{u, max u v}}
    (f g : P ⟶ Q)
    (h : Q ⟶ R)
    (heq : f ≫ h = g ≫ h) :
    CoeqA f g → R.A :=
  Quot.lift h.onShapes (by
    intro x y hxy
    exact coeqDescShape_respects_rel f g h heq hxy)

/-- The induced position map agrees with `h.onShapes` on representatives. -/
@[simp] theorem coeqDescShape_mk
    {R : PolyC.{u, max u v}}
    (f g : P ⟶ Q)
    (h : Q ⟶ R)
    (heq : f ≫ h = g ≫ h)
    (q : Q.A) :
    coeqDescShape f g h heq (coeqClass f g q) = h.onShapes q := by
  rfl

/-- A representative of a component has the expected induced position. -/
private lemma coeqDescShape_eq_of_class
    {R : PolyC.{u, max u v}}
    (f g : P ⟶ Q)
    (h : Q ⟶ R)
    (heq : f ≫ h = g ≫ h)
    (c : CoeqA f g)
    (q : Q.A)
    (hq : coeqClass f g q = c) :
    coeqDescShape f g h heq c = h.onShapes q := by
  cases hq
  rfl

/-
==============================================================================
Step 6: The universal map out of the coequalizer
==============================================================================
-/

/--
The induced map from the coequalizer into any object receiving a coequalizing
map from `Q`.
-/
def coeqDesc
    {R : PolyC.{u, max u v}}
    (f g : P ⟶ Q)
    (h : Q ⟶ R)
    (heq : f ≫ h = g ≫ h) :
    CoeqObj f g ⟶ R where
  onShapes := coeqDescShape f g h heq
  onPos := fun c rdir =>
    ⟨fun q hq =>
        h.onPos q
          (castQPos (Q := R)
            (coeqDescShape_eq_of_class f g h heq c q hq)
            rdir),
      by
        intro p hf hg
        let qf : R.B (h.onShapes (f.onShapes p)) :=
          castQPos (Q := R)
            (coeqDescShape_eq_of_class f g h heq c (f.onShapes p) hf)
            rdir
        let qg : R.B (h.onShapes (g.onShapes p)) :=
          castQPos (Q := R)
            (coeqDescShape_eq_of_class f g h heq c (g.onShapes p) hg)
            rdir
        have hqfg : HEq qf qg := by
          dsimp [qf, qg]
          exact heq_two_castQPos
            (R := R)
            (coeqDescShape_eq_of_class f g h heq c (f.onShapes p) hf)
            (coeqDescShape_eq_of_class f g h heq c (g.onShapes p) hg)
            rdir
        have hComp : (f ≫ h).onPos p qf = (g ≫ h).onPos p qg :=
          hom_onPos_congr
            (F := f ≫ h)
            (G := g ≫ h)
            heq p qf qg hqfg
        simpa [PolyC.comp, qf, qg] using hComp⟩

/-- The induced map factors the original coequalizing arrow. -/
theorem coeqDesc_fac
    {R : PolyC.{u, max u v}}
    (f g : P ⟶ Q)
    (h : Q ⟶ R)
    (heq : f ≫ h = g ≫ h) :
    coeq f g ≫ coeqDesc f g h heq = h := by
  apply Hom.ext
  · funext q
    rfl
  · intro q
    apply heq_of_eq
    funext rdir
    change
      h.onPos q
        (castQPos (Q := R)
          (coeqDescShape_eq_of_class f g h heq (coeqClass f g q) q rfl)
          rdir)
        =
      h.onPos q rdir
    rw [castQPos_eq_self]

/-
==============================================================================
Step 7: Uniqueness of the universal map
==============================================================================
-/

/-- Any other factorization through the coequalizer is equal to `coeqDesc`. -/
theorem coeqDesc_unique
    {R : PolyC.{u, max u v}}
    (f g : P ⟶ Q)
    (h : Q ⟶ R)
    (heq : f ≫ h = g ≫ h)
    (u : CoeqObj f g ⟶ R)
    (hu : coeq f g ≫ u = h) :
    u = coeqDesc f g h heq := by
  have hShapes : u.onShapes = (coeqDesc f g h heq).onShapes := by
    funext c
    refine Quot.inductionOn c ?_
    intro q
    have hs : (coeq f g ≫ u).onShapes q = h.onShapes q :=
      congrArg (fun k => k.onShapes q) hu
    simpa [PolyC.comp, coeq, coeqDesc, coeqDescShape] using hs
  refine Hom.ext u (coeqDesc f g h heq) hShapes ?hDirs
  intro c
  exact heqFunOfCast
    (h := congrArg R.B (congrArg (fun fn => fn c) hShapes))
    (u.onPos c)
    ((coeqDesc f g h heq).onPos c)
    (by
      intro rdir
      apply coeqB_ext
      intro q hq
      cases hq
      let h₁ :
          u.onShapes (coeqClass f g q)
            =
          (coeqDesc f g h heq).onShapes (coeqClass f g q) :=
        congrArg (fun fn => fn (coeqClass f g q)) hShapes
      let h₂ :
          (coeqDesc f g h heq).onShapes (coeqClass f g q)
            =
          h.onShapes q :=
        coeqDescShape_eq_of_class f g h heq (coeqClass f g q) q rfl
      let h₃ :
          u.onShapes (coeqClass f g q) = h.onShapes q := by
        have hs : (coeq f g ≫ u).onShapes q = h.onShapes q :=
          congrArg (fun k => k.onShapes q) hu
        simpa [PolyC.comp, coeq] using hs
      have hComp :
          (coeq f g ≫ u).onPos q rdir
            =
          h.onPos q (cast (congrArg R.B h₃) rdir) :=
        hom_onPos_congr
          (F := coeq f g ≫ u)
          (G := h)
          hu q rdir (cast (congrArg R.B h₃) rdir)
          (heq_cast (congrArg R.B h₃) rdir)
      change
        (u.onPos (coeqClass f g q) rdir).1 q rfl
          =
        h.onPos q
          (castQPos (Q := R) h₂
            (cast (congrArg R.B h₁) rdir))
      rw [castQPos_after_cast_eq (R := R) h₁ h₂ h₃ rdir]
      simpa [PolyC.comp, coeq] using hComp)

/-
==============================================================================
Step 8: The coequalizer universal property
==============================================================================
-/

/-- `CoeqObj f g` with `coeq f g` satisfies the coequalizer universal property. -/
theorem coeqObj_isCoequalizer (f g : P ⟶ Q) :
    IsCoequalizer f g (coeq f g) := by
  refine ⟨coeq_comp_eq f g, ?_⟩
  intro R h heq
  refine ⟨coeqDesc f g h heq, ?factorization, ?uniqueness⟩
  · exact coeqDesc_fac f g h heq
  · intro u hu
    exact coeqDesc_unique f g h heq u hu

/-
==============================================================================
Positions-and-directions summary
==============================================================================
-/

/-- Coequalizer positions are quotient components of positions. -/
def coeqPositionsEquiv (f g : P ⟶ Q) :
    (CoeqObj f g).A ≃ CoeqA f g :=
  Equiv.refl _

/-- Coequalizer directions are compatible families over each position component. -/
def coeqDirectionsEquiv (f g : P ⟶ Q)
    (c : (CoeqObj f g).A) :
    (CoeqObj f g).B c ≃ CoeqB f g c :=
  Equiv.refl _

/-- The coequalizer has the book's positions-and-directions shape. -/
theorem coeq_positions_directions (f g : P ⟶ Q) :
    Nonempty ((CoeqObj f g).A ≃ CoeqA f g)
      ∧
    (∀ c : (CoeqObj f g).A,
      Nonempty ((CoeqObj f g).B c ≃ CoeqB f g c)) := by
  refine ⟨⟨coeqPositionsEquiv f g⟩, ?_⟩
  intro c
  exact ⟨coeqDirectionsEquiv f g c⟩

end CoequalizerConstruction

end PolyC
