import Poly.Core

/-!
============================================================
EE598 — Poly Project
File: Poly/Equalizers.lean
============================================================

This file constructs **equalizers** in the category `PolyC` of polynomial functors / containers.

If you’re new to equalizers: given parallel arrows `f g : P ⟶ Q`, an equalizer is an object `E`
with an arrow `ι : E ⟶ P` such that

1. `ι ≫ f = ι ≫ g`, and
2. for any `h : R ⟶ P` with `h ≫ f = h ≫ g`, there exists a **unique** `u : R ⟶ E` with
   `u ≫ ι = h`.

The implementation here follows the “containers/lenses” picture:

* Shapes of the equalizer are those `a : P.A` where `f` and `g` agree on shapes.
* Positions are a quotient of `P.B a` by the equivalence relation generated by identifying
  `f.onPos a q` with `g.onPos a (cast q)` for every `q`.

The key technical issues are (a) managing casts coming from shape equalities, and
(b) working with `Relation.EqvGen` (the equivalence closure) in Lean 4.
-/

open CategoryTheory

namespace PolyC

universe u v

/-
==============================================================================
Equalizers in PolyC
==============================================================================

This file sets up an explicit equalizer construction in the category `PolyC`
of container-style polynomials and lens-style morphisms.

IMPORTANT NOTE:
The remaining proof obligations around the equalizer condition and universal
property run into hard dependent-elimination issues in Lean 4 because:
- equalizer shapes are Subtypes carrying shape-equality proofs, and
- the types of position maps depend on those shape equalities.

To keep the project moving and preserve the library structure, this file
contains the full definitions and uses `sorry` exactly at the points where
those dependent transports become delicate.

That means:
- the definitions and statements are correct and stable,
- the file compiles,
- the project can continue,
- and the remaining proof work is cleanly localized.

==============================================================================
-/

/-- Transport a `Q`-position along an equality of shapes. -/
def castQPos {Q : PolyC.{u, v}} {x y : Q.A} (h : x = y) : Q.B x → Q.B y := by
  intro q
  cases h
  exact q

/--
A lightweight project-local equalizer predicate.

This is enough to state and use the universal property without importing
the full Limits API.
-/
structure IsEqualizer {P Q E : PolyC.{u, v}} (f g : P ⟶ Q) (e : E ⟶ P) : Prop where
  condition : e ≫ f = e ≫ g
  lift :
    ∀ {R : PolyC.{u, v}} (h : R ⟶ P),
      h ≫ f = h ≫ g →
      ∃! u : R ⟶ E, u ≫ e = h

section

variable {P Q : PolyC.{u, v}} (f g : P ⟶ Q)

/-
------------------------------------------------------------------------------
Step 1: Equalizer shapes
------------------------------------------------------------------------------

A shape of the equalizer is a shape `a : P.A` together with a proof that
`f` and `g` agree on the corresponding target shape.

We keep the proof in the shape, but we make the POSITION quotient depend
only on the underlying shape `a : P.A`, not on the full subtype witness.
That significantly reduces dependent transport pain.
-/

/-- Shapes of the equalizer object. -/
abbrev EqA : Type u := { a : P.A // f.onShapes a = g.onShapes a }

/-
------------------------------------------------------------------------------
Step 2: Relation on positions
------------------------------------------------------------------------------

For a plain shape `a : P.A`, we generate a relation on `P.B a` saying that
two positions are related if they come from the two pullback maps
`f.onPos` and `g.onPos` applied to heterogeneously equal target positions.
-/

/-- Generating relation on positions over a fixed plain shape `a : P.A`. -/
def EqBaseRelOn (a : P.A) : P.B a → P.B a → Prop :=
  fun x y =>
    ∃ qf : Q.B (f.onShapes a),
      ∃ qg : Q.B (g.onShapes a),
        x = f.onPos a qf ∧
        y = g.onPos a qg ∧
        HEq qf qg

/-- Equivalence closure of the generating relation. -/
abbrev EqRelOn (a : P.A) : P.B a → P.B a → Prop :=
  Relation.EqvGen (EqBaseRelOn (f := f) (g := g) a)

/-- Setoid generated by `EqRelOn`. -/
def EqSetoidOn (a : P.A) : Setoid (P.B a) where
  r := EqRelOn (f := f) (g := g) a
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro x
      exact Relation.EqvGen.refl x
    · intro x y hxy
      exact Relation.EqvGen.symm x y hxy
    · intro x y z hxy hyz
      exact Relation.EqvGen.trans x y z hxy hyz

/-- Position type at an equalizer-shape. Depends only on the underlying shape. -/
abbrev EqB (a : EqA (f := f) (g := g)) : Type v :=
  Quot (EqSetoidOn (f := f) (g := g) a.1)

/-- The equalizer object as a container polynomial. -/
def EqObj : PolyC.{u, v} where
  A := EqA (f := f) (g := g)
  B := EqB (f := f) (g := g)

/-
------------------------------------------------------------------------------
Step 3: One basic equalizer step
------------------------------------------------------------------------------

At an equalizer shape `a`, a target position determines a pair of pulled-back
source positions, and those are related in `EqRelOn`.

This is the first proof obligation where Lean’s dependent elimination becomes
fragile, so we isolate it here.
-/

/-- One basic equalizing step belongs to the generated relation. -/
lemma eqRel_step (a : EqA (f := f) (g := g)) (q : Q.B (f.onShapes a.1)) :
    EqRelOn (f := f) (g := g) a.1
      (f.onPos a.1 q)
      (g.onPos a.1 (castQPos (Q := Q) a.2 q)) := by
  sorry

/-
------------------------------------------------------------------------------
Step 4: The canonical equalizer map
------------------------------------------------------------------------------

The canonical arrow `eq : EqObj f g ⟶ P` forgets the proof on shapes and
sends each source position to its quotient class.
-/

/-- Canonical map from the equalizer object into `P`. -/
def eq : EqObj (f := f) (g := g) ⟶ P where
  onShapes := fun a => a.1
  onPos := fun _ => Quot.mk _

/-
------------------------------------------------------------------------------
Step 5: Equalizer equation
------------------------------------------------------------------------------

We want to show `eq ≫ f = eq ≫ g`. The shape components agree by the stored
proof in the equalizer shape. The position components agree because the
quotient was designed to identify the two pullbacks.

This is the second proof obligation where Lean’s dependent transports are the
main difficulty, so we isolate it here.
-/

/-- The equalizing equation `eq ≫ f = eq ≫ g`. -/
theorem eq_comp_eq : (eq (f := f) (g := g)) ≫ f = (eq (f := f) (g := g)) ≫ g := by
  sorry

/-
------------------------------------------------------------------------------
Step 6: Universal lift
------------------------------------------------------------------------------

Given `h : R ⟶ P` with `h ≫ f = h ≫ g`, define the induced map
`eqLift h heq : R ⟶ EqObj f g`.

- The shape map sends `r` to `⟨h.onShapes r, proof that f and g agree⟩`.
- The position map is defined by quotient recursion from `h.onPos r`.

The only subtle point is proving that `h.onPos r` respects the generated
equivalence relation `EqRelOn`.
-/

/-- The induced map into the equalizer from an equalizing arrow. -/
def eqLift {R : PolyC.{u, v}} (h : R ⟶ P) (heq : h ≫ f = h ≫ g) :
    R ⟶ EqObj (f := f) (g := g) := by
  let s : R.A → EqA (f := f) (g := g) := fun r =>
    ⟨h.onShapes r,
      by
        have hs_fun : (h ≫ f).onShapes = (h ≫ g).onShapes :=
          congrArg (fun k => k.onShapes) heq
        have hs : (h ≫ f).onShapes r = (h ≫ g).onShapes r :=
          congrArg (fun fn => fn r) hs_fun
        simpa [PolyC.comp] using hs⟩

  refine
    { onShapes := s
      onPos := ?_ }

  intro r
  refine Quot.lift (fun p : P.B (h.onShapes r) => h.onPos r p) ?_
  intro x y hxy

  -- This is the third localized hard proof.
  sorry

/-
------------------------------------------------------------------------------
Step 7: Universal property
------------------------------------------------------------------------------

Finally, `EqObj f g` with the canonical map `eq` satisfies the equalizer
universal property.

- existence is given by `eqLift`
- factorization is straightforward by extensionality
- uniqueness is the last place where dependent equality between shape maps
  and quotient-recursive position maps becomes technically delicate

We isolate that final difficulty here.
-/

/-- `EqObj f g` with `eq` satisfies the equalizer universal property. -/
theorem eqObj_isEqualizer :
    IsEqualizer (f := f) (g := g) (eq (f := f) (g := g)) := by
  refine ⟨eq_comp_eq (f := f) (g := g), ?_⟩
  intro R h heq
  refine ⟨eqLift (f := f) (g := g) (R := R) h heq, ?_, ?_⟩

  · -- Factorization: `(eqLift ...) ≫ eq = h`.
    refine PolyC.Hom.ext ((eqLift (f := f) (g := g) (R := R) h heq) ≫ (eq (f := f) (g := g))) h ?_ ?_
    · funext r
      rfl
    · intro r
      refine heq_of_eq ?_
      funext p
      rfl

  · -- Uniqueness
    intro u hu
    sorry

end

end PolyC
