import Poly.Pullbacks

/-
============================================================
EE598 — Poly Project
File: Poly/PullbackPositionsDirections.lean
============================================================

This file records the concrete positions-and-directions shape of the
pullback object constructed in `Poly/Pullbacks.lean`.

In `Poly/Pullbacks.lean`, pullbacks are constructed categorically as

  PullObj f g = EqObj (pullLeft f g) (pullRight f g),

where the two comparison maps

  pullLeft  f g : prod P Q ⟶ S,
  pullRight f g : prod P Q ⟶ S

are obtained by projecting out of the product and then applying `f` or `g`.

The book also describes the same pullback directly in the
positions-and-directions presentation:

  • positions are pairs `(p, q)` such that

      f.onShapes p = g.onShapes q;

  • directions at such a position are the pushout of the two direction maps

      S.B (f.onShapes p) → P.B p
      S.B (g.onShapes q) → Q.B q

    induced by `f.onPos` and `g.onPos`.

Because morphisms in `PolyC` pull directions backward, the pushout is
implemented as a quotient of the sum

  P.B p ⊕ Q.B q

by the equivalence relation generated by identifying the two images of a
common direction of `S`.

This file does not rebuild the pullback or reprove its universal property.
It shows that the already-constructed object has exactly the concrete
shape described by the book.

Terminology note:
the codebase still uses the internal field names

  • `A`        = positions,
  • `B a`      = directions at position `a`,
  • `onShapes` = forward map on positions,
  • `onPos`    = backward pullback map on directions.

Human-facing mathematical descriptions should use positions and directions.
============================================================
-/

open CategoryTheory

namespace PolyC

universe u v

section DirectPullbackShape

variable {P Q S : PolyC.{u, v}}

/-
==============================================================================
The explicit pullback position type
==============================================================================
-/

/--
The direct position type of the pullback of `f : P ⟶ S` and `g : Q ⟶ S`.

A position is a pair of positions, one from `P` and one from `Q`, whose
images in the base polynomial `S` agree.
-/
abbrev PullShape (f : P ⟶ S) (g : Q ⟶ S) : Type u :=
  { pq : P.A × Q.A // f.onShapes pq.1 = g.onShapes pq.2 }

/--
The positions of the derived pullback object are exactly the direct pullback
of the position maps.
-/
def pullObjPositionsEquiv (f : P ⟶ S) (g : Q ⟶ S) :
    (PullObj f g).A ≃ PullShape f g where
  toFun a :=
    ⟨a.1,
      by
        simpa [PullObj, pullLeft, pullRight, PolyC.comp] using a.2⟩
  invFun a :=
    ⟨a.1,
      by
        simpa [PullObj, pullLeft, pullRight, PolyC.comp] using a.2⟩
  left_inv := by
    intro a
    apply Subtype.ext
    rfl
  right_inv := by
    intro a
    apply Subtype.ext
    rfl

/-- The first projection on pullback positions is the first component. -/
theorem pullFst_onShapes_direct
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g) :
    (pullFst f g).onShapes ((pullObjPositionsEquiv f g).symm a) = a.1.1 := by
  rfl

/-- The second projection on pullback positions is the second component. -/
theorem pullSnd_onShapes_direct
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g) :
    (pullSnd f g).onShapes ((pullObjPositionsEquiv f g).symm a) = a.1.2 := by
  rfl

/-
==============================================================================
The explicit pushout direction type
==============================================================================
-/

/--
The carrier whose quotient gives the pullback direction type at a direct
pullback position.

It is the sum of the directions from the two legs of the pullback.
-/
abbrev PullDirCarrier
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g) : Type v :=
  Sum (P.B a.1.1) (Q.B a.1.2)

/--
The generating relation for the direction pushout.

This is definitionally the relation used by the equalizer construction on the
product comparison maps, unfolded at the product position `(p, q)`.

Two elements of `P.B p ⊕ Q.B q` are related if they are the left and right
images of heterogeneously equal directions of the common base position in `S`.
-/
abbrev PullDirBaseRel
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g) :
    PullDirCarrier f g a → PullDirCarrier f g a → Prop :=
  EqBaseRelOn (f := pullLeft f g) (g := pullRight f g) a.1

/--
Unfolded form of the generating relation for the direction pushout.
-/
theorem pullDirBaseRel_iff
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g)
    (x y : PullDirCarrier f g a) :
    PullDirBaseRel f g a x y
      ↔
    ∃ sf : S.B (f.onShapes a.1.1),
      ∃ sg : S.B (g.onShapes a.1.2),
        x = Sum.inl (f.onPos a.1.1 sf)
          ∧ y = Sum.inr (g.onPos a.1.2 sg)
          ∧ HEq sf sg := by
  rfl

/-- Equivalence closure of the generating relation for the direction pushout. -/
abbrev PullDirRel
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g) :
    PullDirCarrier f g a → PullDirCarrier f g a → Prop :=
  Relation.EqvGen (PullDirBaseRel f g a)

/-- Setoid generated by the direction-pushout relation. -/
abbrev PullDirSetoid
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g) : Setoid (PullDirCarrier f g a) :=
  EqSetoidOn (f := pullLeft f g) (g := pullRight f g) a.1

/--
The explicit pushout direction type at a pullback position.
-/
abbrev PullDirPushout
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g) : Type v :=
  Quot (PullDirSetoid f g a)

/-- Left inclusion into the direction pushout. -/
def pullDirInl
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g) :
    P.B a.1.1 → PullDirPushout f g a :=
  fun d => Quot.mk _ (Sum.inl d)

/-- Right inclusion into the direction pushout. -/
def pullDirInr
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g) :
    Q.B a.1.2 → PullDirPushout f g a :=
  fun d => Quot.mk _ (Sum.inr d)

/--
The basic pushout equality: the two images of heterogeneously equal base
directions are identified.
-/
theorem pullDirInl_eq_pullDirInr_of_heq
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g)
    (sf : S.B (f.onShapes a.1.1))
    (sg : S.B (g.onShapes a.1.2))
    (hsg : HEq sf sg) :
    pullDirInl f g a (f.onPos a.1.1 sf)
      =
    pullDirInr f g a (g.onPos a.1.2 sg) := by
  apply Quot.sound
  change
    Relation.EqvGen
      (EqBaseRelOn (f := pullLeft f g) (g := pullRight f g) a.1)
      (Sum.inl (f.onPos a.1.1 sf))
      (Sum.inr (g.onPos a.1.2 sg))
  refine Relation.EqvGen.rel
    (r := EqBaseRelOn (f := pullLeft f g) (g := pullRight f g) a.1)
    (x := Sum.inl (f.onPos a.1.1 sf))
    (y := Sum.inr (g.onPos a.1.2 sg))
    ?_
  exact ⟨sf, sg, rfl, rfl, hsg⟩

/--
A casted version of the basic pushout equality, using the equality stored in
the pullback position.
-/
theorem pullDirInl_eq_pullDirInr_cast
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g)
    (s : S.B (f.onShapes a.1.1)) :
    pullDirInl f g a (f.onPos a.1.1 s)
      =
    pullDirInr f g a
      (g.onPos a.1.2 (castQPos (Q := S) a.2 s)) := by
  exact pullDirInl_eq_pullDirInr_of_heq
    f g a s (castQPos (Q := S) a.2 s)
    (castQPos_heq (Q := S) a.2 s)

/-
==============================================================================
Comparison with the derived pullback object's directions
==============================================================================
-/

/--
The directions of the derived pullback object are exactly the explicit pushout
of directions described above.

This is essentially definitional: `PullObj f g` was constructed as an
equalizer of the two comparison maps from the product, and the direction type
of an equalizer is the quotient used here.
-/
def pullObjDirectionsEquiv
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g) :
    (PullObj f g).B ((pullObjPositionsEquiv f g).symm a)
      ≃
    PullDirPushout f g a := by
  change Quot (EqSetoidOn (f := pullLeft f g) (g := pullRight f g) a.1)
      ≃ Quot (PullDirSetoid f g a)
  exact Equiv.refl _

/--
The first projection pulls a direction of `P` into the pushout direction type by
the left quotient inclusion.
-/
theorem pullFst_onPos_direct
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g)
    (d : P.B a.1.1) :
    pullObjDirectionsEquiv f g a
      ((pullFst f g).onPos ((pullObjPositionsEquiv f g).symm a) d)
      =
    pullDirInl f g a d := by
  rfl

/--
The second projection pulls a direction of `Q` into the pushout direction type
by the right quotient inclusion.
-/
theorem pullSnd_onPos_direct
    (f : P ⟶ S) (g : Q ⟶ S)
    (a : PullShape f g)
    (d : Q.B a.1.2) :
    pullObjDirectionsEquiv f g a
      ((pullSnd f g).onPos ((pullObjPositionsEquiv f g).symm a) d)
      =
    pullDirInr f g a d := by
  rfl

/-
==============================================================================
Summary theorem
==============================================================================
-/

/--
The direct positions-and-directions shape of the derived pullback.

This theorem packages the two comparison equivalences:

  • positions of `PullObj f g` are pairs of positions with equal images in `S`;
  • directions at such a position are the pushout quotient of the two direction
    maps into `P` and `Q`.
-/
theorem pullObj_direct_shape
    (f : P ⟶ S) (g : Q ⟶ S) :
    Nonempty
      ((PullObj f g).A ≃ PullShape f g)
      ∧
    (∀ a : PullShape f g,
      Nonempty
        ((PullObj f g).B ((pullObjPositionsEquiv f g).symm a)
          ≃ PullDirPushout f g a)) := by
  refine ⟨⟨pullObjPositionsEquiv f g⟩, ?_⟩
  intro a
  exact ⟨pullObjDirectionsEquiv f g a⟩

end DirectPullbackShape

end PolyC
